export const activityList = [
    'Binge watch an unpopular show',
    'Try Tiktok. \n You know you want to.',
    'Clean up your friends list',
    'Wear the curtains as a dress',
    'Post an embarrassing \n throwback pic',
    'Learn an accent \n and instantly feel interesting',
    'Attempt a high-pitched song',
    'Update your dance moves. \n It’s about time.',
    'Matchmake the spider in the bathroom \n to the one in the kitchen',
    'Be the ultimate memelord \n for a day',
    'Floss. It’s a thing.',
    'Perfect the art of twerking',
    'Write a gratitude list \n and feel awesome',
    'Practice your smoldering look',
    'Say “Irish Wristwatch” 10 times fast',
    'Link surf Wikipedia',
    'Like all your crush’s posts \n even the one from 87 weeks ago',
    'Make a new hashtag famous. \n Suggestion: #makethishashtagfamous',
    'Invent a new flavor',
    'Join a chat group in mIRC. \n It still works.',
    'Find that missing sock',
    'Innovate the macarena',
    'Have a staring contest \n with your pet',
    'Take bathroom selfies',
    'Do sit ups',
    'Howl at your dog \n until he howls back',
    'Sing along to Disney songs',
    'Draw yourself with \n your non-dominant hand',
    'Practice your runway walk',
    'Learn a magic trick',
    'Take a long nap',
    'Update your resume',
    'Rewatch White Chicks',
    'Look at pics of outer space \n and get emotional about \n how small we really are',
    'Type with your nose. \n Just try it.',
    'Fall into an internet wormhole',
    'Find your best angle',
    'Memorize a rap song',
    'Read a book. And finish it.',
    'Do some deep stretches \n (srsly this feels rly good)',
    'Make silly faces and take pics',
    'Chat up a childhood friend',
    'Find out the meaning of the \n Pina Colada song',
    'Look at old family albums',
    'Try to impress your cat',
    'Start an unlikely chat group',
    'Record a video of you saying \n your name backwards. Reverse the video \n and see if you got it right. \n Refine.',
    'Scratch and sniff. \n I leave that up to you.',
    'Watch David Blaine videos. \n Don’t overthink, just enjoy.',
    'Sing Staying Alive and mean it',
    'Look at pics of cute puppies \n while holding a squishy pillow',
    'Write a haiku',
    'Learn sign language',
    'Try a beatboxing tutorial',
    'Check your horoscope',
]