export const activityList = [
    'Play with your pet',
    'Binge watch something',
    'Sing to lyric videos',
    'Try Tiktok',
    'Take bathroom selfies',
    'Facetime your friends',
    'Work on your dance moves',
    'Do situps',
    'Take a nap',
    'Practice your runway walk',
    'Floss',
    'Learn a magic trick',
    'Wear the curtains as a dress',
    'Post a throwback pic',
    'Watch cat videos',
    'Read a book',
    'Clean up your friends list',
    'Look at old family albums',
    'Do your nails',
    'Say a prayer of thanks',
    'Fall into an internet wormhole',
    'Find your best angle',
    'Memorize a rap song',
    'Bake something',
    'Try beatboxing',
    'Make silly faces',
    'Check your horoscope',
    'Learn an accent',
    'Chat up a childhood friend',
    'Draw yourself',
    'Change your profile pic',
    'Attempt a high-pitched song',
    'Count 1 to 1000',
]